name: Java CI with Maven Build AEM repository

on:
  push:
    branches: [ main, develop, add-missing-submodules ]
  pull_request:
    branches: [ main, develop, add-missing-submodules ]

jobs:
  aem-build:
    uses: CruGlobal/.github/.github/workflows/aem-cloud-build.yml@v1
    secrets:
        aem-cloud-artifactory-user: ${{ secrets.AEM_CLOUD_ARTIFACTORY_USER }}
        aem-cloud-artifactory-api-key: ${{ secrets.AEM_CLOUD_ARTIFACTORY_API_KEY }}

